---
swagger: "2.0"
info:
  version: "2021-08-22T10:11:45Z"
  title: "product-service-dev"
host: "48i2ud2ps6.execute-api.eu-central-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /products:
    get:
      responses: {}
  /products/{id}:
    get:
      responses: {}
